## Numpy

In [32]:
import numpy as np

In [33]:
a = np.array([1, 2, 3, 4, 'a', True])
print(a)

['1' '2' '3' '4' 'a' 'True']


In [34]:
x = np.arange(64)

In [35]:
x.reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [36]:
x.reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [37]:
np.max(x)

np.int64(63)

In [38]:
np.mean(x)

np.float64(31.5)

In [39]:
np.min(x)

np.int64(0)

In [40]:
np.std(x)

np.float64(18.472953201911167)

In [41]:
type(x)

numpy.ndarray

## Pandas

In [42]:
import pandas as pd

In [43]:
array = np.arange(0,100).reshape(10,10)

In [44]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [46]:
df = pd.DataFrame(array, index=['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'], columns=['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10'])
df

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [50]:
df.c1 > 11

r1     False
r2     False
r3      True
r4      True
r5      True
r6      True
r7      True
r8      True
r9      True
r10     True
Name: c1, dtype: bool

In [55]:
df[df['c1'] > 50][['c1', 'c5']]

c1  c5
r7   60  64
r8   70  74
r9   80  84
r10  90  94

In [ ]:
c1 > 11 AND c1 < 80

SyntaxError: invalid syntax (2680527209.py, line 1)

In [66]:
df[(df.c1 > 30) & (df.c1 < 70)]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r5  40  41  42  43  44  45  46  47  48   49
r6  50  51  52  53  54  55  56  57  58   59
r7  60  61  62  63  64  65  66  67  68   69

In [70]:
df[(df.c1 > 60) & (df.c2 > 80)]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [71]:
df[(df.c1 > 60) | (df.c2 > 80)]

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [72]:
df.describe()

c1         c2         c3         c4         c5         c6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

              c7         c8         c9        c10  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000

In [74]:
df.sample(5)

c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r8  70  71  72  73  74  75  76  77  78   79
r3  20  21  22  23  24  25  26  27  28   29
r2  10  11  12  13  14  15  16  17  18   19
r6  50  51  52  53  54  55  56  57  58   59

In [76]:
df = pd.read_csv("C:\\Users\\Student\\Desktop\\breast-cancer-detection-master\\breast-cancer-data.csv")

In [78]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [86]:
df.iloc[100:105, :]

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
100  862717         M       13.610         24.98           88.05      582.7   
101  862722         B        6.981         13.43           43.79      143.5   
102  862965         B       12.180         20.52           77.22      458.7   
103  862980         B        9.876         19.40           63.95      298.3   
104  862989         B       10.490         19.29           67.41      336.1   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
100          0.09488           0.08511         0.08625              0.04489   
101          0.11700           0.07568         0.00000              0.00000   
102          0.08013           0.04038         0.02383              0.01770   
103          0.10050           0.09697         0.06154              0.03029   
104          0.09989           0.08578         0.02995              0.01201   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
100  ...          35.27           108.60       906.5            0.1265   
101  ...          19.54            50.41       185.2            0.1584   
102  ...          32.84            84.58       547.8            0.1123   
103  ...          26.83            72.22       361.2            0.1559   
104  ...          23.31            74.22       402.8            0.1219   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
100            0.19430          0.31690               0.11840          0.2651   
101            0.12020          0.00000               0.00000          0.2932   
102            0.08862          0.11450               0.07431          0.2694   
103            0.23020          0.26440               0.09749          0.2622   
104            0.14860          0.07987               0.03203          0.2826   

     fractal_dimension_worst  Unnamed: 32  
100                  0.07397          NaN  
101                  0.09382          NaN  
102                  0.06878          NaN  
103                  0.08490          NaN  
104                  0.07552          NaN  

[5 rows x 33 columns]