In [124]:
import numpy as np
import pandas as pd

In [125]:
x = np.array([10,13,21,22,31])

In [126]:
x[3]

22

In [127]:
a = np.array(54) # 0D

b = np.array([10,13,21,22,31]) #1D

c = np.array([[1,2,3,4],[5,6,7,8]]) #2D

d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #3D

In [128]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [129]:
a = np.array(42)
print("Array Dimension: ", a.ndim ,"D")
print(a)
print("-------------------------")


b = np.array([1, 2, 3, 4, 5])
print("Array Dimension: ", b.ndim ,"D")
print(b)
print("-------------------------")


c = np.array([[2,4,5,8], [3,1,5,7], [2,6,8,1]])
print("Array Dimension: ", c.ndim ,"D")
print(c)
print("-------------------------")


d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("Array Dimension: ", d.ndim ,"D")
print(d)
print("-------------------------")

Array Dimension:  0 D
42
-------------------------
Array Dimension:  1 D
[1 2 3 4 5]
-------------------------
Array Dimension:  2 D
[[2 4 5 8]
 [3 1 5 7]
 [2 6 8 1]]
-------------------------
Array Dimension:  3 D
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
-------------------------


In [130]:
c

array([[2, 4, 5, 8],
       [3, 1, 5, 7],
       [2, 6, 8, 1]])

In [131]:
c[1:3,1:3]

array([[1, 5],
       [6, 8]])

In [132]:
c.sum()

52

In [133]:
c.sum(axis=1)

array([19, 16, 17])

In [134]:
c

array([[2, 4, 5, 8],
       [3, 1, 5, 7],
       [2, 6, 8, 1]])

In [135]:
c[:,1].sum()

11

In [136]:
np.sum(c[1:,1:3])

20

In [137]:
c

array([[2, 4, 5, 8],
       [3, 1, 5, 7],
       [2, 6, 8, 1]])

In [138]:
np.median(c)

4.5

In [139]:
c.std()

2.4608038433722337

In [140]:
c.sum()

52

In [141]:
import random

x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
x = np.random.randint(1,50, size=(3,4))
x

array([[20, 40, 36, 32],
       [37, 36,  7, 28],
       [13, 41, 46, 29]])

In [161]:
x = np.random.rand(3,4)*100
x

array([[37.0914081 , 59.25312531, 79.83703243, 75.80343287],
       [ 9.35727881, 64.01854576, 59.58759901, 82.76714999],
       [35.97826249, 22.05114446, 48.03200001,  6.38810899]])

In [162]:
y = np.random.random(12).reshape(3,4)*100
y

array([[79.80401233, 99.05680815, 87.37101753, 23.41673793],
       [65.14741869, 48.7398353 , 63.12739191, 60.84943735],
       [39.71682051, 51.40002532, 88.00809347, 51.09583637]])

In [163]:
c

array([[2, 4, 5, 8],
       [3, 1, 5, 7],
       [2, 6, 8, 1]])

In [165]:
x

array([[20, 40, 36, 32],
       [37, 36,  7, 28],
       [13, 41, 46, 29]])

In [166]:
x + c

array([[22, 44, 41, 40],
       [40, 37, 12, 35],
       [15, 47, 54, 30]])

In [182]:
m = np.arange(10)
m = np.resize(m, (3, 4))
m


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1]])

In [183]:
x

array([[20, 40, 36, 32],
       [37, 36,  7, 28],
       [13, 41, 46, 29]])

In [184]:
m

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1]])

In [187]:
np.vstack((x,m))

array([[20, 40, 36, 32],
       [37, 36,  7, 28],
       [13, 41, 46, 29],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9,  0,  1]])

In [188]:
np.hstack((x,m))

array([[20, 40, 36, 32,  0,  1,  2,  3],
       [37, 36,  7, 28,  4,  5,  6,  7],
       [13, 41, 46, 29,  8,  9,  0,  1]])

In [ ]:
np.arange()