# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [1]:
# Lets create a Python list. 
my_list = [-1,0,1] 

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [5]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix_one.shape

In [ ]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [7]:
num = np.arange(100) # similar to range() in Python, not including 100  
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [9]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [ ]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 20, 40, retstep=True)

In [ ]:
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace

In [ ]:
np.linspace(1,2,30) # 1-D array 

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [18]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
x.shape

(16,)

In [22]:
x.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
y = x.reshape(4, 2, 2)
y

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [25]:
y.shape

(4, 2, 2)

In [ ]:
x = y.reshape(4,4)

In [ ]:
x

In [ ]:
x.shape

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [27]:
np.random.rand(4) # 1-D array with three elements

array([0.94359887, 0.60574017, 0.56499933, 0.1405783 ])

In [ ]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [28]:
np.random.randn(20, 5)

array([[-0.16930674,  0.03314569,  1.63900608,  2.65612063, -0.87658444],
       [-0.16514563,  0.34284074, -0.05862598, -0.235784  , -1.290354  ],
       [ 0.01421546, -0.37077665,  0.32578213, -1.60257509,  0.23516346],
       [ 1.41169937, -0.0534353 ,  2.48259641, -0.25231497,  2.12890605],
       [-2.18156085,  0.69448134, -1.27534899, -0.37599756, -0.3508271 ],
       [ 1.06226446,  0.07391306, -0.88627235,  1.22301116,  1.14255148],
       [ 0.96211859,  0.78911962,  0.43352094,  0.15802868,  0.57615969],
       [ 0.80636745,  0.61099087, -0.44479645,  0.28924014,  1.44011512],
       [ 0.19094252,  1.28165535,  1.3780859 , -1.38554096, -2.08845637],
       [-0.34076171,  0.22130665,  0.37891683,  0.21778486,  1.00008465],
       [ 1.3014922 ,  0.20620003,  1.19911068,  0.17953568, -0.58777621],
       [ 0.7473594 , -0.26239252, -0.17882038, -2.02907991,  0.28506043],
       [-1.27604331, -0.3849306 , -1.22446867, -0.79390222, -0.02587199],
       [ 2.29103635, -0.2781625 , -0.9

In [ ]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

In [ ]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

In [ ]:
df['A'].hist(bins=30)

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1, 2000, 50) #returns one random int, 1 inclusive, 100 exclusive

In [ ]:
np.random.randint(100,200,20).reshape(4,5) #returns ten random int,

In [ ]:
arr0 = np.random.randint(low=1000, high=2000, size=[5,8])
arr0

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [2]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [3]:
array_ranint

array([68, 25, 74, 46,  4, 83, 25, 49, 79, 48])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [39]:
array_ranint.min()

5

In [40]:
array_ranint.max()

81

In [42]:
array_ranint.mean()
#np.mean(array_ranint)

50.5

In [43]:
np.median(array_ranint)

56.0

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [44]:
array_ranint.argmax() # index starts from 0

8

In [45]:
array_ranint.argmin()

6

### Attributes
* `size, shape, dtype` 

In [4]:
array_arange = np.arange(16)

In [5]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
array_arange.shape

(16,)

In [ ]:
array_arange.size

In [ ]:
# Size of the array 
array_arange.itemsize

In [ ]:
# Type of the data.
array_arange.dtype

In [ ]:
array_arange.reshape(4,4)

In [ ]:
array_arange

In [ ]:
array_arange.shape = (4,4)

In [ ]:
array_arange

In [ ]:
array_arange = array_arange.reshape(16,)

In [ ]:
array_arange

### Indexing & slicing of 1-D arrays (vectors)

In [ ]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [ ]:
array_1d

In [ ]:
array_1d[2]

In [ ]:
# Getting a range value
array_1d[0:3]

In [ ]:
# Using -ve index 
array_1d[-2]

In [ ]:
# Using -ve index for a range 
array_1d[1:]

In [ ]:
array_1d

In [ ]:
array_1d[:2]

In [ ]:
array_1d[2:]

In [ ]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [ ]:
array_1d
# The first element is changed to -102

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [ ]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [ ]:
# To get a complete row
array_2d[2]

In [ ]:
array_2d[-4] 

In [ ]:
array_2d

In [ ]:
# another way 
row = 5
column = 2
array_2d[row, column]

In [ ]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

In [ ]:
array_2d

In [ ]:
# 2D array slicing
array_2d[:2,:2] 

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [ ]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [ ]:
array_1d[0:5] = 500 
array_1d

In [ ]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

In [ ]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

In [ ]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d * np.arange(0,4)  #[0,1,2,3]

In [ ]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

In [ ]:
array_2d

In [ ]:
array_2d[[3, 1]]  
#array_2d[3, 1]

In [ ]:
array_2d[:,[2]]

In [ ]:
array_2d

In [ ]:
# We can use any order
array_2d[[3, 1]]

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

In [ ]:
# grabbing rows
array_2d[[2,3]] #[2][3]

In [ ]:
array_2d[:3, [2,3]]

In [ ]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

In [ ]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

We can apply condition such as >, <, == etc

In [ ]:
array_1d > 3

In [ ]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

Lets create a mask to **filter out the even numbers in "array_1d"**

In [ ]:
array_1d % 2

In [ ]:
0 == array_1d % 2

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

In [ ]:
array_1d

In [ ]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [ ]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

In [ ]:
# Subtracting two arrays
arr - arr

In [ ]:
# Multiplication
arr * arr

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

In [ ]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

In [ ]:
# Power of all the elements in an array
arr ** 2

In [ ]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [ ]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

In [ ]:
# max and min values
np.max(arr), np.min(arr)

In [ ]:
arr.max()

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

**Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d.sum()

In [ ]:
array_2d.sum(axis=1)

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d.std()

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d

In [ ]:
array_2d % 3 == 0

In [ ]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

In [ ]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

In [ ]:
np.zeros(5)